FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update

RUN apt-get install r-base -y && \
    apt-get install gdebi-core -y && \
    apt-get install -y wget

RUN wget https://download2.rstudio.org/server/focal/amd64/rstudio-server-2023.12.1-402-amd64.deb

RUN gdebi rstudio-server-2023.12.1-402-amd64.deb

COPY . ./rscripts
WORKDIR /
EXPOSE 8787
ENV USER=rstudio
CMD ["/usr/lib/rstudio-server/bin/rserver", "--server-daemonize=0", "--server-app-armor-enabled=0"]